package com.dcw.app.rating.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dcw.app.rating.db.bean.Box;
import com.dcw.app.rating.db.bean.UserBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig boxDaoConfig;
    private final DaoConfig userBeanDaoConfig;

    private final BoxDao boxDao;
    private final UserBeanDao userBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        boxDaoConfig = daoConfigMap.get(BoxDao.class).clone();
        boxDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        boxDao = new BoxDao(boxDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);

        registerDao(Box.class, boxDao);
        registerDao(UserBean.class, userBeanDao);
    }
    
    public void clear() {
        boxDaoConfig.getIdentityScope().clear();
        userBeanDaoConfig.getIdentityScope().clear();
    }

    public BoxDao getBoxDao() {
        return boxDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

}
